### ISSUE TITLE
FEAT: Implement groupby nth

### ISSUE THREAD

**Issue by codingl2k1** [xorbitsai/xorbits#634]
### Is your feature request related to a problem? Please describe

https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.nth.html

**Comment by Abhijeet1520** [comment]
Hello, if no one else is working on it then can I take over this issue?

**Comment by aresnow1** [comment]
> Hello, if no one else is working on it then can I take over this issue?

Sure, you can reply take and issue will be assigned to you.
