### ISSUE TITLE
BUG: Unable to successfully start the generated xorbits web service

### ISSUE THREAD

**Issue by YELineee** [xorbitsai/xorbits#664]
### Describe the bug

I'm having trouble creating a web service using the ' xorbits.init(init_local=True ,web=True) ' and can't successfully open the resulting web service. (This page isn’t working HTTP ERROR 502)

```python
import xorbits
import xorbits.numpy as np

xorbits.init(init_local=True ,web=True)
print(np.random.rand(100, 100).mean())
```

### To Reproduce

To help us to reproduce this bug, please provide information below:

1. Your Python version ----> 3.11.4
2. The version of Xorbits you use ----->0.5.1

**Comment by ChengjieLi28** [comment]
Hi, @YELineee . I have tried your code on Python 3.11.
<img width="1432" alt="image" src="https://github.com/xorbitsai/xorbits/assets/109656400/7794d0b0-1734-423a-ba47-4e0c74d54265">
And I can open the web UI according to the log.

Please check your network setting (maybe you have some VPN settings) or provide more specific information for us to debug. Thanks.

**Comment by YELineee** [comment]
Thanks
