### ISSUE TITLE
BUG: How to read local csv file

### ISSUE THREAD

**Issue by YishuiLi** [xorbitsai/xorbits#763]
### Describe the bug
Create a cluster with one supervisor and two workers on CentOS7, then connection this cluster in windows 10 and read local csv file with xorbits.pandas.read_csv, but got FileNotFoundError exception. How to read local csv file?

### To Reproduce
1. **Python 3.8.18**
2. **Xorbits 0.7.1**
3. numpy and pandas
a. **pandas 2.0.3**
b. **numpy 1.24.4**
4. Full stack of the error.
![image](https://github.com/xorbitsai/xorbits/assets/16732930/b44b5aaa-8af1-4355-ad53-5e70180f3287)
![image](https://github.com/xorbitsai/xorbits/assets/16732930/31b3a0e6-6933-43ec-8d57-5bd56d373614)

5. Minimized code to reproduce the error.
```
import xorbits
import xorbits.pandas as pd

xorbits.init('http://192.168.2.130:7005')
df = pd.read_csv(r"F:\dataset\iris.csv", header=0, sep=",", encoding="utf-8")
xorbits.run(df)

```

**Comment by qinxuye** [comment]
FileNotFoundError, can you check if the file exists?

**Comment by YishuiLi** [comment]
> FileNotFoundError, can you check if the file exists?

File exists in the local computer, but not in the cluster. How to read this local csv file? Does every node require file transfers?

**Comment by qinxuye** [comment]
You need to store the file in the object store, like hdfs or oss etc, ensure the file can be seen in the cluster.

**Comment by YishuiLi** [comment]
> You need to store the file in the object store, like hdfs or oss etc, ensure the file can be seen in the cluster.

Got it. Thanks!
